name: Deploy regionala_utvecklingsmedel

on:
  push:
    branches: [ publicera ]

jobs:
  deploy:
    runs-on: [ self-hosted, shiny ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy app using server-side script
        run: |
          TEMP_DIR="${GITHUB_WORKSPACE}/app"
          /usr/local/bin/shiny_deploy.sh regionala_utvecklingsmedel "$TEMP_DIR"
